name: "HDK Task"
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      preset_prefix:
        required: true
        type: string

jobs:
  hdk_task:
    strategy:
      matrix:
        build_config: [debug, release]
        compiler: [g++-11, clang++-12]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: 'Install G++-11'
        run: sudo apt install gcc-11 g++-11
        if: ${{matrix.compiler == 'g++-11'}}
      - name: 'Configure HDK CMake Project'
        run: cmake --preset ${{inputs.preset_prefix}}${{matrix.build_config}} -DCMAKE_CXX_COMPILER=${{matrix.compiler}}
      - name: 'Build ${{inputs.target}}'
        run: cmake --build ./build/debug --target ${{inputs.target}}
