name: "HDK Unit Tests"
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  code_build:
    uses: ./.github/workflows/hdk.yml
    with:
      target: hdktest
      preset_prefix: ci-
      build_msvc: false
